prSections:
  - title: My Pull Requests
    filters: is:open
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
notificationsSections:
  - title: All
    filters: ""
  - title: Created
    filters: reason:author
  - title: Participating
    filters: reason:participating
  - title: Mentioned
    filters: reason:mention
  - title: Review Requested
    filters: reason:review-requested
  - title: Assigned
    filters: reason:assign
  - title: Subscribed
    filters: reason:subscribed
  - title: Team Mentioned
    filters: reason:team-mention
repo:
  branchesRefetchIntervalSeconds: 30
  prsRefetchIntervalSeconds: 60
defaults:
  preview:
    open: false
    width: 100
  prsLimit: 20
  prApproveComment: LGTM
  issuesLimit: 20
  notificationsLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 20
      author:
        width: 15
      authorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 15
    issues:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 15
      creator:
        width: 10
      creatorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  universal:
    - key: G
      name: lazygit
      command: >
        cd {{.RepoPath}}; lazygit
    - key: T
      name: code enhance
      command: gh enhance -R {{.RepoName}} {{.PrNumber}}
  prs:
    - key: D
      name: hunk diff
      command: gh diff

theme:
  colors:
    text:
      primary: "#ebfafa"
      secondary: "#a48cf2"
      inverted: "#212337"
      faint: "#7081d0"
      warning: "#e9f941"
      success: "#37f499"
      error: "#f9515d"
    background:
      selected: "#2a2c48"
    border:
      primary: "#a48cf2"
      secondary: "#7081d0"
      faint: "#2a2c48"
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
      compact: true
pager:
  diff: "diffnav"
confirmQuit: false
showAuthorIcons: true
smartFilteringAtLaunch: true
