prSections:
  - title: My PRs
    filters: is:open
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
notificationsSections:
  - title: All
    filters: ""
  - title: Created
    filters: reason:author
  - title: Participating
    filters: reason:participating
  - title: Mentioned
    filters: reason:mention
  - title: Review Requested
    filters: reason:review-requested
  - title: Assigned
    filters: reason:assign
  - title: Subscribed
    filters: reason:subscribed
  - title: Team Mentioned
    filters: reason:team-mention
repo:
  branchesRefetchIntervalSeconds: 30
  prsRefetchIntervalSeconds: 60
defaults:
  preview:
    open: false
    width: 100
  prsLimit: 25
  prApproveComment: LGTM
  issuesLimit: 25
  notificationsLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 20
      author:
        width: 15
      authorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 15
    issues:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 15
      creator:
        width: 10
      creatorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  universal:
    - key: G
      name: lazygit
      command: >
        cd {{.RepoPath}}; lazygit
    - key: T
      name: code enhance
      command: gh enhance -R {{.RepoName}} {{.PrNumber}}
  prs:
    - key: D
      name: hunk diff
      command: gh diff
    - key: m
      name: squash merge
      command: gh pr merge --squash --delete-branch --repo {{.RepoName}} {{.PrNumber}}

theme:
  colors:
    text:
      primary: "#f8f8f2"
      secondary: "#bd93f9"
      inverted: "#282a36"
      faint: "#6272a4"
      warning: "#f1fa8c"
      success: "#50fa7b"
      error: "#ff5555"
    background:
      selected: "#44475a"
    border:
      primary: "#bd93f9"
      secondary: "#6272a4"
      faint: "#21222c"
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
      compact: true
pager:
  diff: "diffnav"
confirmQuit: false
showAuthorIcons: true
smartFilteringAtLaunch: true
