---
prSections:
  - title: My Pull Requests
    filters: is:open author:@me
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
defaults:
  preview:
    open: true
    width: 100
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 15
      title:
        grow: true
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      title:
        grow: true
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  issues: []
  prs: 
    - key: T
      command: gh enhance -R {{.RepoName}} {{.PrNumber}}
repoPaths: {}
theme:
  ui:
    table:
      showSeparator: true
  colors:
    text:
      primary: "#FFFFFF"
      secondary: "#FFC799"
      inverted: "#101010"
      faint: "#A0A0A0"
      warning: "#FFCFA8"
      success: "#99FFE4"
      error: "#FF8080"
    background:
      selected: "#232323"
    border:
      primary: "#FFC799"
      secondary: "#505050"
      faint: "#282828"
pager:
  # diff: hunk diff
  diff: diffnav
confirmQuit: false
