# vim:ft=kitty
## name: Eldritch Dusk
## author: jacobrreed
## license: MIT
## upstream: https://github.com/eldritch-theme/eldritch
## blurb: Eldritch light (Dusk) variant
foreground            #1e2029
background            #f0f3f4
selection_foreground  #1e2029
selection_background  #e2e6e8

url_color #0ad6ff

# black
color0  #c9cbcd
color8  #5b73dc

# red
color1  #fb5b66
color9  #fb5b66

# green
color2  #38ff9f
color10 #38ff9f

# yellow
color3  #fff952
color11 #ffaf4d

# blue
color4   #8a69f7
color12  #8a69f7

# magenta
color5  #fb5bb6
color13 #fb5bb6

# cyan
color6  #0ad6ff
color14 #0ad6ff

# white
color7  #1e2029
color15 #1e2029

# Cursor colors
cursor #38ff9f
cursor_text_color #f0f3f4

# Tab bar colors
active_tab_foreground   #f0f3f4
active_tab_background   #38ff9f
inactive_tab_foreground #5b73dc
inactive_tab_background #e2e6e8

# Marks
mark1_foreground #f0f3f4
mark1_background #fb5b66

# Splits/Windows
active_border_color #8a69f7
inactive_border_color #c9cbcd
