## name: Tokyo Night
## author: folke
## license: MIT
## upstream: https://github.com/folke/tokyonight.nvim/blob/main/extras/kitty/tokyonight_night.conf
## blurb: A clean, dark theme that celebrates the lights of downtown Tokyo at night

foreground               #c0caf5
background               #1a1b26
selection_foreground     #c0caf5
selection_background     #283457

url_color                #73daca

cursor                   #c0caf5
cursor_text_color        #1a1b26

active_tab_foreground    #1a1b26
active_tab_background    #7aa2f7
inactive_tab_foreground  #545c7e
inactive_tab_background  #1a1b26

# black
color0   #15161e
color8   #414868

# red
color1   #f7768e
color9   #f7768e

# green
color2   #9ece6a
color10  #9ece6a

# yellow
color3   #e0af68
color11  #e0af68

# blue
color4   #7aa2f7
color12  #7aa2f7

# magenta
color5   #bb9af7
color13  #bb9af7

# cyan
color6   #7dcfff
color14  #7dcfff

# white
color7   #a9b1d6
color15  #c0caf5
