# Catppuccin Mocha theme
# https://github.com/catppuccin/wezterm
[colors]
ansi = [
  '#45475a',
  '#f38ba8',
  '#a6e3a1',
  '#f9e2af',
  '#89b4fa',
  '#f5c2e7',
  '#94e2d5',
  '#bac2de',
]
background = '#1e1e2e'
brights = [
  '#585b70',
  '#f38ba8',
  '#a6e3a1',
  '#f9e2af',
  '#89b4fa',
  '#f5c2e7',
  '#94e2d5',
  '#a6adc8',
]
compose_cursor = '#f2cdcd'
cursor_bg = '#f5e0dc'
cursor_border = '#f5e0dc'
cursor_fg = '#1e1e2e'
foreground = '#cdd6f4'
scrollbar_thumb = '#cba6f7'
selection_bg = '#585b70'
selection_fg = '#cdd6f4'
split = '#6c7086'

[colors.indexed]

[colors.tab_bar]
background = '#1e1e2e'

[colors.tab_bar.active_tab]
bg_color = '#cba6f7'
fg_color = '#11111b'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#181825'
fg_color = '#7f849c'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#cba6f7'
fg_color = '#11111b'
intensity = 'Normal'
italic = true
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#181825'
fg_color = '#cdd6f4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#cba6f7'
fg_color = '#cdd6f4'
intensity = 'Normal'
italic = true
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'Catppuccin'
name = 'Catppuccin Mocha'
origin_url = 'https://github.com/catppuccin/wezterm'
