onboarding = false

[experimental]
allow_nested = true
kitty_graphics = true

[theme]
name = "terminal"

[ui]
show_agent_labels_on_pane_borders = true

[ui.toast]
enabled = true
delivery = "terminal"

[ui.sound]
enabled = true
path = "sounds/notification.mp3"
done_path = "sounds/done.mp3"
request_path = "sounds/request.mp3"

[keys]
prefix = "control+alt+,"
detach = "prefix+d"
resize_mode = "prefix+r"
toggle_sidebar = "prefix+b"

fullscreen = "prefix+f"
split_vertical = "prefix+\\"
split_horizontal = "prefix+-"

new_tab = "prefix+t"
rename_tab = "prefix+shift+t"
next_tab = "control+alt+l"
previous_tab = "control+alt+h"

new_workspace = "prefix+n"
rename_workspace = "prefix+shift+e"
close_workspace = "prefix+shift+w"
next_workspace = "control+alt+i"
previous_workspace = "control+alt+u"

previous_agent = "control+alt+k"
next_agent = "control+alt+j"

close_pane = "prefix+x"
rename_pane = "prefix+p"
focus_pane_left = "control+shift+alt+h"
focus_pane_up = "control+shift+alt+k"
focus_pane_down = "control+shift+alt+j"
focus_pane_right = "control+shift+alt+l"

[[keys.command]]
key = "prefix+g"
type = "pane"
command = "lazygit"

[[keys.command]]
key = "prefix+y"
type = "pane"
command = "yazi"
