onboarding = false

[experimental]
allow_nested = true
kitty_graphics = true
resume_agents_on_restore = true
pane_history = false

[theme]
name = "terminal"

[ui]
show_agent_labels_on_pane_borders = true

[ui.toast]
enabled = true
delivery = "terminal"

[ui.sound]
enabled = true
path = "sounds/notification.mp3"
done_path = "sounds/done.mp3"
request_path = "sounds/request.mp3"

[keys]
prefix = "alt+control+,"
detach = "prefix+d"
resize_mode = "prefix+r"
toggle_sidebar = "prefix+b"

goto=""
edit_scrollback =""
new_worktree=""

fullscreen = "prefix+f"
split_vertical = "prefix+\\"
split_horizontal = "prefix+-"

new_tab = "prefix+t"
next_tab = "alt+control+l"
previous_tab = "alt+control+h"
rename_tab = "prefix+e"

new_workspace = "prefix+n"
close_workspace = "prefix+shift+w"
next_workspace = "alt+control+i"
previous_workspace = "alt+control+u"
rename_workspace = "prefix+shift+e"

previous_agent = "alt+control+k"
next_agent = "alt+control+j"

close_pane = "prefix+x"
focus_pane_left = "alt+control+shift+h"
focus_pane_up = "alt+control+shift+k"
focus_pane_down = "alt+control+shift+j"
focus_pane_right = "alt+control+shift+l"
rename_pane = "prefix+p"

[[keys.command]]
key = "prefix+g"
type = "pane"
command = "lazygit"

[[keys.command]]
key = "prefix+/"
type = "pane"
command = "git diff | diffnav --unified"

[[keys.command]]
key = "prefix+y"
type = "pane"
command = "yazi"
