  colors:
    text:
      primary: "#cdd6f4"
      secondary: "#cba6f7"
      inverted: "#1e1e2e"
      faint: "#7f849c"
      warning: "#f9e2af"
      success: "#a6e3a1"
      error: "#f38ba8"
    background:
      selected: "#313244"
    border:
      primary: "#cba6f7"
      secondary: "#7f849c"
      faint: "#181825"
