  colors:
    text:
      primary: "#4c4f69"
      secondary: "#8839ef"
      inverted: "#eff1f5"
      faint: "#8c8fa1"
      warning: "#df8e1d"
      success: "#40a02b"
      error: "#d20f39"
    background:
      selected: "#ccd0da"
    border:
      primary: "#8839ef"
      secondary: "#8c8fa1"
      faint: "#dce0e8"
