  colors:
    text:
      primary: "#c0caf5"
      secondary: "#7aa2f7"
      inverted: "#1a1b26"
      faint: "#565f89"
      warning: "#e0af68"
      success: "#9ece6a"
      error: "#f7768e"
    background:
      selected: "#283457"
    border:
      primary: "#7aa2f7"
      secondary: "#414868"
      faint: "#292e42"
