  theme:
    activeBorderColor:
      - "#bd93f9"
      - bold
    inactiveBorderColor:
      - "#6272a4"
    searchingActiveBorderColor:
      - "#bd93f9"
      - bold
    optionsTextColor:
      - "#8be9fd"
    selectedLineBgColor:
      - "#44475a"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#bd93f9"
    cherryPickedCommitBgColor:
      - "#6272a4"
    markedBaseCommitFgColor:
      - "#6272a4"
    markedBaseCommitBgColor:
      - "#f1fa8c"
    unstagedChangesColor:
      - "#ff5555"
    defaultFgColor:
      - "#f8f8f2"
