  theme:
    activeBorderColor:
      - "#fabd2f"
      - bold
    inactiveBorderColor:
      - "#928374"
    searchingActiveBorderColor:
      - "#fabd2f"
      - bold
    optionsTextColor:
      - "#83a598"
    selectedLineBgColor:
      - "#504945"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#d3869b"
    cherryPickedCommitBgColor:
      - "#458588"
    markedBaseCommitFgColor:
      - "#458588"
    markedBaseCommitBgColor:
      - "#fabd2f"
    unstagedChangesColor:
      - "#fb4934"
    defaultFgColor:
      - "#ebdbb2"
