colourful: true

filekinds:
  normal: {foreground: "#c6d0f5"}
  directory: {foreground: "#eebebe"}
  symlink: {foreground: "#8caaee"}
  pipe: {foreground: "#b5bfe2"}
  block_device: {foreground: "#ea999c"}
  char_device: {foreground: "#ea999c"}
  socket: {foreground: "#b5bfe2"}
  special: {foreground: "#ca9ee6"}
  executable: {foreground: "#a6d189"}
  mount_point: {foreground: "#81c8be"}

perms:
  user_read: {foreground: "#e78284", is_bold: true}
  user_write: {foreground: "#e5c890", is_bold: true}
  user_execute_file: {foreground: "#a6d189", is_bold: true}
  user_execute_other: {foreground: "#a6d189", is_bold: true}
  group_read: {foreground: "#e78284"}
  group_write: {foreground: "#e5c890"}
  group_execute: {foreground: "#a6d189"}
  other_read: {foreground: "#e78284"}
  other_write: {foreground: "#e5c890"}
  other_execute: {foreground: "#a6d189"}
  special_user_file: {foreground: "#ca9ee6"}
  special_other: {foreground: "#838ba7"}
  attribute: {foreground: "#949cbb"}

size:
  major: {foreground: "#a5adce"}
  minor: {foreground: "#99d1db"}
  number_byte: {foreground: "#b5bfe2"}
  number_kilo: {foreground: "#a5adce"}
  number_mega: {foreground: "#8caaee"}
  number_giga: {foreground: "#ca9ee6"}
  number_huge: {foreground: "#ca9ee6"}
  unit_byte: {foreground: "#a5adce"}
  unit_kilo: {foreground: "#99d1db"}
  unit_mega: {foreground: "#ca9ee6"}
  unit_giga: {foreground: "#ca9ee6"}
  unit_huge: {foreground: "#81c8be"}

users:
  user_you: {foreground: "#c6d0f5"}
  user_root: {foreground: "#e78284"}
  user_other: {foreground: "#ea999c"}
  group_yours: {foreground: "#a5adce"}
  group_other: {foreground: "#949cbb"}
  group_root: {foreground: "#e78284"}

links:
  normal: {foreground: "#8caaee"}
  multi_link_file: {foreground: "#8caaee"}

git:
  new: {foreground: "#a6d189"}
  modified: {foreground: "#e5c890"}
  deleted: {foreground: "#ea999c"}
  renamed: {foreground: "#81c8be"}
  typechange: {foreground: "#f4b8e4"}
  ignored: {foreground: "#838ba7"}
  conflicted: {foreground: "#ef9f76"}

git_repo:
  branch_main: {foreground: "#a5adce"}
  branch_other: {foreground: "#ca9ee6"}
  git_clean: {foreground: "#a6d189"}
  git_dirty: {foreground: "#ea999c"}

security_context:
  colon: {foreground: "#737994"}
  user: {foreground: "#838ba7"}
  role: {foreground: "#ca9ee6"}
  typ: {foreground: "#626880"}
  range: {foreground: "#ca9ee6"}

file_type:
  image: {foreground: "#e5c890"}
  video: {foreground: "#e78284"}
  music: {foreground: "#a6d189"}
  lossless: {foreground: "#81c8be"}
  crypto: {foreground: "#838ba7"}
  document: {foreground: "#c6d0f5"}
  compressed: {foreground: "#f4b8e4"}
  temp: {foreground: "#ea999c"}
  compiled: {foreground: "#85c1dc"}
  source: {foreground: "#8caaee"}

punctuation: {foreground: "#737994"}
date: {foreground: "#e5c890"}
inode: {foreground: "#a5adce"}
blocks: {foreground: "#737994"}
header: {foreground: "#c6d0f5"}
octal: {foreground: "#81c8be"}
flags: {foreground: "#ca9ee6"}

symlink_path: {foreground: "#99d1db"}
control_char: {foreground: "#85c1dc"}
broken_symlink: {foreground: "#e78284"}
broken_path_overlay: {foreground: "#626880"}
