vim.treesitter.language.register("json", "jsonc")

return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "astro",
      "bash",
      "c",
      "cpp",
      "css",
      "dockerfile",
      "fish",
      "git_config",
      "gitignore",
      "go",
      "graphql",
      "html",
      "javascript",
      "jsdoc",
      "json",
      "json5",
      "jsonc",
      "lua",
      "markdown",
      "markdown_inline",
      "php",
      "python",
      "regex",
      "rust",
      "scss",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "yaml",
    },
  },
}
