[colors.primary]
background = '#212337'
foreground = '#ebfafa'

[colors.cursor]
cursor = '#37f499'
text = '#f8f8f2'

[colors.normal]
black = '#21222c'
blue = '#9071f4'
cyan = '#04d1f9'
green = '#37f499'
magenta = '#f265b5'
red = '#f9515d'
white = '#ebfafa'
yellow = '#e9f941'

[colors.bright]
black = '#7081d0'
blue = '#a48cf2'
cyan = '#66e4fd'
green = '#69f8b3'
magenta = '#fd92ce'
red = '#f16c75'
white = '#ffffff'
yellow = '#f1fc79'

[colors.selection]
background = '#bf4f8e'
text = '#ebfafa'
