#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
console_title_template = "{{ .Folder }}"
final_space = true
version = 2.0

[[blocks]]
alignment = "left"
type = "prompt"

[[blocks.segments]]
foreground = "#333"
style = "plain"
template = "\u256d\u2500"
type = "text"

[[blocks.segments]]
background = "#222"
foreground = "#555"
leading_diamond = "\ue0b6"
style = "diamond"
template = "{{ if matchP \"D:\" .Path }}Dev{{ else }}{{ end }}"
trailing_diamond = "\ue0b4 "
type = "path"

[[blocks.segments]]
alias = "path"
background = "#fdc734"
foreground = "transparent"
leading_diamond = "\ue0b6"
style = "diamond"
template = "\ue5ff {{ .Path }} "
trailing_diamond = "\ue0b4"
type = "path"
[blocks.segments.properties]
style = "folder"

[[blocks.segments]]
leading_diamond = "<#222,> \ue0b6</>"
style = "diamond"
template = "<#e3caff,#222>\uf09b </><#222,#1a1a1a>\ue0c4</><#e3caff,#1a1a1a> {{ .HEAD }} </>"
trailing_diamond = ""
type = "git"

[[blocks.segments]]
background = "#222"
background_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}#ffc734{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ffe190{{ end }}",
  "{{ if gt .Ahead 0 }}#56248f{{ end }}",
  "{{ if gt .Behind 0 }}#56248f{{ end }}",
]
foreground = "#e3caff"
foreground_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}#222{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#222{{ end }}",
  "{{ if gt .Ahead 0 }}#e3caff{{ end }}",
  "{{ if gt .Behind 0 }}#e3caff{{ end }}",
]
leading_diamond = ""
style = "diamond"
template = "<#e3caff,#222>{{ if .Working.Changed }} \uf044 {{ .Working.String }} {{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }} {{ end }}{{ if gt .StashCount 0 }} \ueb4b {{ .StashCount }} {{ end }}</>{{ if .BranchStatus }} {{ .BranchStatus }}{{ end }}"
trailing_diamond = "\ue0b4"
type = "git"
[blocks.segments.properties]
branch_max_length = 25.0
fetch_stash_count = true
fetch_status = true
fetch_upstream_icon = true

[[blocks.segments]]
background = "#56248f"
foreground = "#e3caff"
leading_diamond = " \ue0b6"
style = "diamond"
template = "\ue77f "
trailing_diamond = "\ue0b4"
type = "dotnet"

[[blocks.segments]]
background = "#331655"
foreground = "#e3caff"
leading_diamond = ""
style = "diamond"
template = " {{ .Full }}"
trailing_diamond = "\ue0b4"
type = "dotnet"
[blocks.segments.properties]
display_mode = "files"

[[blocks]]
alignment = "right"
type = "rprompt"

[[blocks.segments]]
alias = "Status"
style = "plain"
template = "{{if .Error }}<#fa113d>\uf057 </>{{else}}<#1ca350>\uf058 </>{{end}}"
type = "status"
[blocks.segments.properties]
always_enabled = true

[[blocks.segments]]
style = "plain"
template = "{{if .Segments.Status.Error }}<#fa113d>{{ .FormattedMs }}</>{{else}}<#1ca350>{{ .FormattedMs }}</>{{end}} "
type = "executiontime"
[blocks.segments.properties]
always_enabled = true
style = "austin"
threshold = 500.0

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

[[blocks.segments]]
foreground = "#333"
style = "plain"
template = "\u2570\u2500"
type = "text"
