import = ["~/.config/alacritty/themes/lunar-eclipse.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "transparent"
padding.x = 10
padding.y = 25
opacity = 0.85
blur = true
dynamic_title = true
option_as_alt = "Both"

[font]
normal.family = "SauceCodePro Nerd Font"
normal.style = "Regular"
bold.style = "Bold"
italic.style = "Italic"
size = 18

[mouse]
hide_when_typing = true

[cursor]
thickness = 0.10
blink_interval = 500
blink_timeout = 0

[cursor.style]
blinking = "Always"

### keyboard bindings ###
# new instance of alacritty in root
[[keyboard.bindings]]
key = "N"
mods = "Command|Shift"
action = "SpawnNewInstance"
# kill window
[[keyboard.bindings]]
key = "="
mods = "Command|Control"
action = "Quit"
# macos natural text editing
