import = [
  "~/.config/alacritty/themes/lunar-eclipse.toml",
  "~/.config/alacritty/keybindings.toml"
  ]
[env]
TERM = "xterm-256color"

[window]
blur = true
decorations = "Buttonless"
dynamic_title = true
dimensions.columns = 135
dimensions.lines = 41
opacity = 0.9
padding.x = 10
padding.y = 5

option_as_alt = "Both"

[font]
normal.family = "FiraCode Nerd Font Mono"
normal.style = "Regular"
bold.style = "Bold"
italic.style = "Italic"
size = 16

[mouse]
hide_when_typing = true
[selection]
save_to_clipboard = true

[cursor]
thickness = 0.10
blink_interval = 500
blink_timeout = 0
style.blinking = "Always"
