import = [
  "~/.config/alacritty/themes/atelier-lakeside-dark.toml",
  "~/.config/alacritty/keybindings.toml",
]

[env]
TERM = "xterm-256color"

[window]
blur = true
decorations = "Buttonless"
opacity = 0.9
option_as_alt = "Both"
dimensions = { columns = 120, lines = 30 }
padding = { x = 10, y = 5 }
position = { x = 670, y = 413 }

[scrolling]
history = 25000

[font]
size = 16
offset = { x = 1, y = 1 }
normal = { family = "Cascadia Code NF", style = "Light" }
bold.style = "Bold"
italic.style = "Italic"

[mouse]
hide_when_typing = true
[selection]
save_to_clipboard = true

[cursor]
blink_interval = 500
blink_timeout = 0
style.blinking = "Always"
style.shape = "Block"

[debug]
log_level = "Off"
