### keyboard bindings - MacOS natural text editing ###
[keyboard]
bindings = [
  # new instance of alacritty in root
  { key = "N", mods = "Command|Shift", action = "SpawnNewInstance" },
  # kill window
  { key = "=", mods = "Command|Control", action = "Quit" },
  # open config with ⌘ + ,
  { key = ",", mods = "Command", action = "Open" },
  # delete entire line with ⌘ + backspace
  { key = "Back", mods = "Command", chars = "\u0015" },
  # move cursor to next/previous word with ⌥ + left/right
  { key = "Left", mods = "Alt", chars = "\u001bD" },
  { key = "Right", mods = "Alt", chars = "\u001bC" },
  # jump to beginning/end of line with ⌘ + left/right
  { key = "Left", mods = "Command", chars = "\u001bOH" },
  { key = "Right", mods = "Command", chars = "\u001bOF" },
]
