### keyboard bindings - MacOS natural text editing ###
[keyboard]
bindings = [
  # new instance of alacritty in root
  { key = "N", mods = "Command|Shift", action = "SpawnNewInstance" },
  # kill window
  { key = "=", mods = "Command|Control", action = "Quit" },
  { key = "W", mods = "Command|Shift", action = "Quit" },
  # open config with ⌘ + ,
  # delete entire line with ⌘ + backspace
  { key = "Back", mods = "Command", chars = "\u0015" },
  # jump to beginning/end of line with ⌘ + left/right
  { key = "Left", mods = "Command", chars = "\u001bOH" },
  { key = "Right", mods = "Command", chars = "\u001bOF" },
]
