# Setting up the Path
set -e fish_user_paths

# Homebrew generated by `brew shellenv`
set -gx HOMEBREW_PREFIX "/opt/homebrew";
set -gx HOMEBREW_CELLAR "/opt/homebrew/Cellar";
set -gx HOMEBREW_REPOSITORY "/opt/homebrew";
set -q PATH; or set PATH ''; set -gx PATH "/opt/homebrew/bin" "/opt/homebrew/sbin" $PATH;
set -q MANPATH; or set MANPATH ''; set -gx MANPATH "/opt/homebrew/share/man" $MANPATH;
set -q INFOPATH; or set INFOPATH ''; set -gx INFOPATH "/opt/homebrew/share/info" $INFOPATH;

#set -U fish_user_paths "/usr/local/sbin" $fish_user_paths #homebrew
set -g fish_user_paths "/opt/homebrew/bin" $fish_user_paths # homebrew ARM

#rust
set -U fish_user_paths $HOME/.cargo/bin $fish_user_paths

# rbenv
# set -Ux fish_user_paths $HOME/.rbenv/bin $fish_user_paths
# eval (rbenv init - | source )

# openssl to path
set -g fish_user_paths "/opt/homebrew/opt/openssl@1.1/bin" $fish_user_paths

# Custom sourcing of colors, exports, grc, multi-function fish files
source ~/.config/fish/conf.d/__imports.fish

# Start Starship Prompt
starship init fish | source

# Vim Mode
fish_vi_key_bindings
# Homebrew Ruby
set -g fish_user_paths "/opt/homebrew/opt/ruby/bin" $fish_user_paths
set -g fish_user_paths $HOME/.gem/ruby/3.0.0/bin $fish_user_paths
set -g fish_user_paths  $HOME/.fig/bin $fish_user_paths
