format = "$all"
right_format = "$cmd_duration"

command_timeout = 500
scan_timeout = 100

[battery]
disabled = true

## start character ##
[character]
success_symbol = '[](bold #37F499)'
error_symbol = '[](bold #F16C75)'

[shell]
fish_indicator = ""
unknown_indicator = "?"
style = "bold fg:white"
disabled = true
## end character ##

## start prompt ##
[directory]
format = "[⚡︎](#04D1F9)[$path]($style)[$read_only]($read_only_style) "
read_only = " "
truncation_symbol = "…󰿟"

[git_branch]
style = "#F265B5"
symbol = " "
format = "on [$symbol$branch(:$remote_branch)]($style)[ ≡]($style) "

[git_metrics]
disabled = false
added_style = "#37F499"
deleted_style = "#F16C75"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
style = "white"
format = "([$all_status$ahead_behind]($style) )"
conflicted = "[ ](fg:red bg:bright-black)"
ahead = "[ ×${count} ](white)"
behind = "[ ×${count} ](white)"
diverged = "[ ×${ahead_count} ×${behind_count} ](bg:bright-black)"
untracked = "️[ ×${count} ](#04D1F9)"
stashed = " "
modified = "[ ×${count} ](#F1FC79)"
staged = "[ ×${count} ](bright-green)"
deleted = "[ ×${count} ](bright-red)"
renamed = "[ ×${count} ](#F7C67F)"

[cmd_duration]
disabled = false
min_time = 1
format = "[󰔛 $duration]($style)"
show_milliseconds = true
style = "#7081BE"
## end prompt ##

## start custom symbols ##
[package]
symbol = "󰏗 "

[aws]
style = "#F7C67F"
format = "[$symbol($version )]($style)"
symbol = "  "

[deno]
format = "[$symbol($version )]($style)"
style = "#7081BE"
symbol = "󱍢 "

[nodejs]
format = "[$symbol($version )]($style)"
style = "#37F499"
symbol = "󰎙 "
detect_extensions = []

[bun]
format = "[$symbol($version )]($style)"
style = "#EBFAFA"
symbol = " "
detect_extensions = []

[golang]
style = "#04D1F9"
format = "[$symbol($version )]($style)"
symbol = " "

[lua]
style = "#04D1F9"
format = "[$symbol($version )]($style)"
symbol = " "

[php]
style = "#A48CF2"
format = "[$symbol($version )]($style)"
symbol = " "

[python]
style = "#F1FC79"
format = "[$symbol($version )]($style)"
symbol = " "

[ruby]
style = "#F16C75"
format = "[$symbol($version )]($style)"
symbol = "󰴭 "

[rust]
style = "#F7C67F"
format = "[$symbol($version )]($style)"
symbol = " "
## end custom symbols ##
