[include]
# paths = ["/etc/topgrade.toml"]

[misc]
pre_sudo = false
disable = [
  "system",
  "vscode",
  "containers",
  "ruby_gems",
  "gem",
  "tlmgr",
  "node",
  "pnpm",
  "yarn",
  "shell",
  "cargo",
  "rustup",
  "pipx",
  "pyenv",
  "microsoft_office",
  "antigravity",
]
ignore_failures = ["bun_packages"]
assume_yes = true
no_retry = true
cleanup = true
skip_notify = true

# Custom Pre-commands
# [pre_commands]

# Custom commands
[commands]
"Fisher Plugins" = "fisher update &>/dev/null; and echo 'Fisher Update Complete'"
"LazyVim Plugins" = "nvim --headless -c 'Lazy! sync' +qa &>/dev/null; and echo 'LazyVim Plugins Update Complete'"
"Treesitter Parsers" = "nvim --headless -c 'sleep 100m' -c 'TSUpdate' -c 'qa' &>/dev/null; and echo 'Treesitter Update Complete'"

# Custom Post-commands
[post_commands]
"Brew - Cleanup" = "brew cleanup --prune=all &>/dev/null; and echo 'Brew Cleanup Complete'"

[composer]
self_update = true

[brew]
greedy_cask = true
autoremove = true

[git]
repos = [
  "~/Developer/AI/herdr/",
  "~/Developer/AI/Fabric/",
  "~/Developer/AI/gstack/",
  "~/Developer/AI/claude-seo/",
  "~/Developer/AI/claude-obsidian/",
  "~/Developer/AI/claude-cybersecurity/",
  "~/Developer/AI/PAI/",
]
